import 'package:indoor_navigation/domain/tiled/tiled_models.dart';

const turnRoutePath = <OverlayRouteNode>[
  OverlayRouteNode(
    id: 1,
    nodeId: 'A',
    screenX: 0,
    screenY: 0,
    tiledX: 0,
    tiledY: 0,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 2,
    nodeId: 'B',
    screenX: 100,
    screenY: 0,
    tiledX: 100,
    tiledY: 0,
    type: 'junctions',
  ),
  OverlayRouteNode(
    id: 3,
    nodeId: 'C',
    screenX: 100,
    screenY: 100,
    tiledX: 100,
    tiledY: 100,
    type: 'route-node',
  ),
];

const atTurnBeforeUserTurns = RoutePosition(
  distanceAlongRoute: 100,
  headingDegrees: 0,
  screenX: 100,
  screenY: 0,
  segmentIndex: 0,
  tiledX: 100,
  tiledY: 0,
);

const demoRoutePath = <OverlayRouteNode>[
  OverlayRouteNode(
    id: 21,
    nodeId: 'node-21',
    screenX: 236,
    screenY: 648,
    tiledX: -20,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 20,
    nodeId: 'node-20',
    screenX: 369,
    screenY: 648,
    tiledX: 113,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 19,
    nodeId: 'node-19',
    screenX: 606,
    screenY: 648,
    tiledX: 350,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 18,
    nodeId: 'node-18',
    screenX: 829,
    screenY: 648,
    tiledX: 573,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 17,
    nodeId: 'node-17',
    screenX: 1048,
    screenY: 648,
    tiledX: 792,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 16,
    nodeId: 'node-16',
    screenX: 1248,
    screenY: 648,
    tiledX: 992,
    tiledY: 904,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 12,
    nodeId: 'node-12',
    screenX: 1248,
    screenY: 877,
    tiledX: 992,
    tiledY: 1133,
    type: 'junctions',
  ),
  OverlayRouteNode(
    id: 13,
    nodeId: 'node-13',
    screenX: 829,
    screenY: 877,
    tiledX: 573,
    tiledY: 1133,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 14,
    nodeId: 'node-14',
    screenX: 606,
    screenY: 877,
    tiledX: 350,
    tiledY: 1133,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 15,
    nodeId: 'node-15',
    screenX: 369,
    screenY: 877,
    tiledX: 113,
    tiledY: 1133,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 2,
    nodeId: 'node-2',
    screenX: 176,
    screenY: 877,
    tiledX: -80,
    tiledY: 1133,
    type: 'route-node',
  ),
  OverlayRouteNode(
    id: 1,
    nodeId: 'node-1',
    screenX: 176,
    screenY: 648,
    tiledX: -80,
    tiledY: 904,
    type: 'route-node',
  ),
];
