import 'package:indoor_navigation/domain/campus/campus_floor.dart';
import 'package:indoor_navigation/domain/campus/campus_room.dart';

const mainCampusBuildingName = 'Main Campus Building';
const mainCampusDefaultFloorId = 'floor-3';

const mainCampusFloors = <CampusFloor>[
  CampusFloor(
    code: 'F1',
    id: 'floor-1',
    name: 'Ground Floor',
    plan: CampusFloorPlan.ground,
    summary: 'Entrance & Dining',
    tags: ['Cafeteria', 'Retail', 'Lobby'],
  ),
  CampusFloor(
    code: 'F2',
    id: 'floor-2',
    name: 'Second Floor',
    plan: CampusFloorPlan.second,
    summary: 'Recreation & Work',
    tags: ['Gym', 'Study Area', 'Meeting Rooms'],
  ),
  CampusFloor(
    code: 'F3',
    id: 'floor-3',
    name: 'Third Floor',
    plan: CampusFloorPlan.third,
    suggested: true,
    summary: 'Academics',
    tags: ['Classrooms', 'Library', 'Computer Lab'],
  ),
  CampusFloor(
    code: 'F4',
    id: 'floor-4',
    name: 'Fourth Floor',
    plan: CampusFloorPlan.fourth,
    summary: 'Events & Rest',
    tags: ['Event Hall', 'Seminar Rooms', 'Rest Area'],
  ),
];

const mainCampusRooms = <CampusRoom>[
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-1',
    id: 'cafeteria-cf101',
    name: 'Cafeteria',
    roomCode: 'CF101',
    typeLabel: 'Dining',
    visual: CampusRoomVisual.cafeteria,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-1',
    id: 'main-lobby-l101',
    name: 'Main Lobby',
    roomCode: 'L101',
    typeLabel: 'Lobby',
    visual: CampusRoomVisual.generic,
    walkMinutes: 1,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-1',
    id: 'campus-store-r102',
    name: 'Campus Store',
    roomCode: 'R102',
    typeLabel: 'Retail',
    visual: CampusRoomVisual.generic,
    walkMinutes: 3,
  ),
  CampusRoom(
    category: CampusRoomCategory.restroom,
    floorId: 'floor-1',
    id: 'restroom-w101',
    name: 'Restroom',
    roomCode: 'W101',
    typeLabel: 'Restroom',
    visual: CampusRoomVisual.restroom,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-2',
    id: 'gym-g201',
    name: 'Gym',
    roomCode: 'G201',
    typeLabel: 'Recreation',
    visual: CampusRoomVisual.gym,
    walkMinutes: 3,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-2',
    id: 'study-area-s205',
    name: 'Study Area',
    roomCode: 'S205',
    typeLabel: 'Study Area',
    visual: CampusRoomVisual.library,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.classroom,
    floorId: 'floor-2',
    id: 'meeting-room-m204',
    name: 'Meeting Room',
    roomCode: 'M204',
    typeLabel: 'Classroom',
    visual: CampusRoomVisual.generic,
    walkMinutes: 4,
  ),
  CampusRoom(
    category: CampusRoomCategory.restroom,
    floorId: 'floor-2',
    id: 'restroom-w201',
    name: 'Restroom',
    roomCode: 'W201',
    typeLabel: 'Restroom',
    visual: CampusRoomVisual.restroom,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.lab,
    floorId: 'floor-3',
    id: 'computer-lab-c301',
    name: 'Computer Lab',
    roomCode: 'C301',
    typeLabel: 'Lab',
    visual: CampusRoomVisual.computerLab,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-3',
    id: 'library-l305',
    name: 'Library',
    roomCode: 'L305',
    typeLabel: 'Study Area',
    visual: CampusRoomVisual.library,
    walkMinutes: 3,
  ),
  CampusRoom(
    category: CampusRoomCategory.classroom,
    floorId: 'floor-3',
    id: 'lecture-hall-h302',
    name: 'Lecture Hall A',
    roomCode: 'H302',
    typeLabel: 'Classroom',
    visual: CampusRoomVisual.lectureHall,
    walkMinutes: 1,
  ),
  CampusRoom(
    category: CampusRoomCategory.lab,
    floorId: 'floor-3',
    id: 'research-lab-r304',
    name: 'Research Lab',
    roomCode: 'R304',
    typeLabel: 'Lab',
    visual: CampusRoomVisual.researchLab,
    walkMinutes: 4,
  ),
  CampusRoom(
    category: CampusRoomCategory.restroom,
    floorId: 'floor-3',
    id: 'restroom-w301',
    name: 'Restroom',
    roomCode: 'W301',
    typeLabel: 'Restroom',
    visual: CampusRoomVisual.restroom,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-4',
    id: 'event-hall-e401',
    name: 'Event Hall',
    roomCode: 'E401',
    typeLabel: 'Facility',
    visual: CampusRoomVisual.generic,
    walkMinutes: 3,
  ),
  CampusRoom(
    category: CampusRoomCategory.classroom,
    floorId: 'floor-4',
    id: 'seminar-room-s402',
    name: 'Seminar Room',
    roomCode: 'S402',
    typeLabel: 'Classroom',
    visual: CampusRoomVisual.lectureHall,
    walkMinutes: 4,
  ),
  CampusRoom(
    category: CampusRoomCategory.facility,
    floorId: 'floor-4',
    id: 'rest-area-r405',
    name: 'Rest Area',
    roomCode: 'R405',
    typeLabel: 'Facility',
    visual: CampusRoomVisual.generic,
    walkMinutes: 2,
  ),
  CampusRoom(
    category: CampusRoomCategory.restroom,
    floorId: 'floor-4',
    id: 'restroom-w401',
    name: 'Restroom',
    roomCode: 'W401',
    typeLabel: 'Restroom',
    visual: CampusRoomVisual.restroom,
    walkMinutes: 2,
  ),
];
